name: Build Windows Executable

on:
  # Permet de lancer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:
  # Se déclenche automatiquement à chaque push sur la branche main
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Récupère le code de votre dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Installe Python sur la machine virtuelle Windows
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Installe les dépendances du projet et PyInstaller
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    # 4. Lance PyInstaller pour créer l'exécutable
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name="Analyseur_Pointage" gui.py

    # 5. Met en ligne le .exe pour que vous puissiez le télécharger
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Analyseur-Pointage-Windows
        path: dist/Analyseur_Pointage.exe